### PR TITLE
Mac OS support

### PR DESCRIPTION
**Pull request by bunkovic**
Added support for MacOs

### CODE REVIEW

**Comment by tomaszbak** [comment]
It would be nice to include link for the docs for the desktop support. The one thing that caught my eye is this:
https://flutter.dev/desktop

> To make it easier to try out Desktop support for Flutter, we are shipping a snapshot of Flutter beta channel’s Desktop support in Flutter 2 stable. This means that you can easily try it out without needing to switch to the Flutter beta channel. However, the snapshot included in the stable channel will not be updated with the latest Flutter support for Desktop until the next Flutter stable release.

**Comment by bunkovic** [comment]
> It would be nice to include link for the docs for the desktop support. The one thing that caught my eye is this:
> https://flutter.dev/desktop
> 
> > To make it easier to try out Desktop support for Flutter, we are shipping a snapshot of Flutter beta channel’s Desktop support in Flutter 2 stable. This means that you can easily try it out without needing to switch to the Flutter beta channel. However, the snapshot included in the stable channel will not be updated with the latest Flutter support for Desktop until the next Flutter stable release.

You mean like mention that in the README.md?

**Comment by tomaszbak** [comment]
> > It would be nice to include link for the docs for the desktop support. The one thing that caught my eye is this:
> > https://flutter.dev/desktop
> > > To make it easier to try out Desktop support for Flutter, we are shipping a snapshot of Flutter beta channel’s Desktop support in Flutter 2 stable. This means that you can easily try it out without needing to switch to the Flutter beta channel. However, the snapshot included in the stable channel will not be updated with the latest Flutter support for Desktop until the next Flutter stable release.
> 
> You mean like mention that in the README.md?

README is also a good place, but I was thinking about PR description and later in the commit description. Idea is to make it explicit that macOS desktop support is beta feature.

**Review by tomaszbak — APPROVED** [review]

**Pull request merged**
